In [3]:
%matplotlib inline
import matplotlib.pyplot as plt
from math import sin
import pandas as pd
import os
import numpy as np

In [15]:
train = True
loanDB = pd.read_csv('data/loanUnitedTrain.csv') if train else pd.read_csv('data/loanUnitedTest.csv')

failed = loanDB[loanDB["loan_success"] == -1]
f_different = failed[failed["account_district code "] != failed["client_district code "]]

p = len(f_different)/len(failed)

success = loanDB[loanDB["loan_success"] == 1]
s_different = success[success["account_district code "] != success["client_district code "]]

p2 = len(s_different)/len(success)

plt.title("Accounts with registred in the same district as the client that didn't payed back the loan")
plt.pie([p, 1-p], labels=["Not same district","Same district"], autopct='%1.1f%%')
plt.savefig("images/DU/loan_fail_distric_same")

plt.title("Accounts with registred in the same district as the client that payed back the loan")
plt.pie([p2, 1-p2], labels=["Not same district","Same district"], autopct='%1.1f%%')
plt.pie([p2, 1-p2])
plt.savefig("images/DU/loan_success_distric_same")

plt.scatter(success["account_district code "],success.index)
plt.scatter(failed["account_district code "],failed.index)
plt.savefig("images/DU/district_success_vs_loan")

plt.scatter(success["account_district region"],success.index)
plt.scatter(failed["account_district region"],failed.index)
plt.savefig("images/DU/region_success_vs_loan")

plt.pie(success.pivot_table(columns=["women"], aggfunc="size"), labels=["women","men"], autopct='%1.1f%%')
plt.savefig("images/DU/loan_success_men_vs_women")

plt.pie(failed.pivot_table(columns=["women"], aggfunc="size"), labels=["women","men"], autopct='%1.1f%%')
plt.savefig("images/DU/loan_fail_men_vs_women")

plt.scatter(success["account_frequency"],success.index, color="green")
plt.scatter(failed["account_frequency"],failed.index, color="red")
plt.savefig("images/DU/loan_success_vs_fail_account_frequency")

In [17]:
drops = ["birthday"]

drops_subsstrs = ["date", "code"]

drops += [c for c in loanDB.columns if True in [s in c for s in drops_subsstrs]]
final = loanDB.drop(columns=drops)
final.to_csv("data/final_loan_train.csv", index=False)
final

,amount,loan_duration,payments,loan_success,disposition_type,account_frequency,account_creation,account_district region,account_district no. of inhabitants,account_district no. of municipalities with inhabitants < 499,...,card issue,no. of transactions,balance,nr_movements,min_trans_amount,max_trans_amount,avg_trans_amount,min_balance,max_balance,avg_balance
0,96396,12,8033,-1,OWNER,weekly issuance,930322,west Bohemia,94812,15,...,0,3300.0,20100.0,4.0,1100.0,9900.0,5025.000000,1100.0,20100.0,12250.000000
1,165960,36,4610,1,OWNER,monthly issuance,930213,east Bohemia,112709,48,...,0,3419.0,52208.9,37.0,2.9,54300.0,11015.635135,700.0,120512.8,52083.859459
2,127080,60,2118,1,OWNER,monthly issuance,930208,east Bohemia,77917,85,...,0,12000.0,20272.8,24.0,48.6,19065.0,5417.458333,800.0,49590.4,30060.954167
3,105804,36,2939,1,OWNER,monthly issuance,930130,central Bohemia,107870,84,...,0,14.6,34292.7,25.0,14.6,26448.0,8253.080000,1000.0,65898.5,41297.480000
4,274740,60,4579,1,OWNER,weekly issuance,930214,Prague,1204953,0,...,0,182.8,41142.9,27.0,30.0,63366.0,18945.966667,600.0,122893.1,57188.211111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,155616,48,3242,1,OWNER,monthly issuance,950121,north Moravia,226122,32,...,0,14600.0,60694.1,172.0,14.6,36960.0,4895.974419,200.0,75294.1,44197.509884
324,222180,60,3703,-1,OWNER,monthly issuance,951129,west Bohemia,45714,52,...,0,6900.0,59578.8,59.0,14.6,52600.0,11725.494915,800.0,130659.1,55230.444068
325,45024,48,938,1,OWNER,monthly issuance,960521,north Moravia,285387,0,...,0,17800.0,38384.3,39.0,14.6,31636.5,7779.815385,800.0,63659.3,41994.907692
326,115812,36,3217,1,OWNER,monthly issuance,950520,south Bohemia,93931,74,...,0,3100.0,41878.1,124.0,14.6,50800.0,13280.084677,1100.0,119527.2,56646.516129
327,129408,24,5392,1,OWNER,monthly issuance,951014,north Moravia,106054,38,...,0,4780.0,24199.5,107.0,14.6,24212.0,4550.302804,1000.0,56055.6,30869.781308